# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [@torproject, @cspire]
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective open sea.io
ko_fi: # Replace with a single Ko-fi https://www.facebook.com/profile.php?id=100043903929161
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/npm install --save-dev @babel/preset-react
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay https://booking.com
issuehunt: # Replace with a single IssueHunt https://mypillow.com
otechie: # Replace with a single Otechie https://libertymutual.com
custom: # Replace with up to 4 custom sponsorship URLs https://McDonalds.com., ['https://starbucks.app.link/y7CPRFzxV2?$3p=a_custom_717388981498776555&dclid=CLWdiJLe-OYCFcx3wQodcvcBNg', 'https://goarmy.com']
